### PR TITLE
Added some missing C99 float operations - Windows, etc.

### PR DESCRIPTION
**Pull request by dra27**
Using a separate PR to allow discussion of these additions before merging into the main PR. This branch has been through [precheck#587](https://ci.inria.fr/ocaml/job/precheck/587/).

I've made the following alterations:

- Use `AC_CHECK_FUNCS` (as is done for the sockets functions) rather than a sea of `AS_IF`. This has the benefit of making the special case for `fma` clearer as well.
- Visual Studio 2012 and earlier do not have these functions, so for those specifically I've made omitting `--enable-imprecise-c99-float-ops` a warning rather than a hard error.
- I've refactored the lib-float test so that it always runs all the tests (like the fma test). That doesn't have to be merged here, but my reason for including it is that it would be good to update it to have some tests for these new functions. That said, that doesn't _have_ to be done right now (i.e. I don't think the PR should fail to make 4.13 because of missing tests).
- Visual Studio 2013 (which is used on the precheck machines at Inria) have all of these functions, but `fma` is broken (as it is on Cygwin). mingw-w64 8.0.0 has actually introduced a breakage into their `fma` function and `round` has been broken on mingw-w64 for several years (I've linked the bug reports for both). However, the VS 2015+ functions appear to be working just fine as are all the other functions on mingw-w64 and Cygwin. I've therefore made a special case for `round` in the same way as `fma`.
- At the moment, if `round` doesn't work then the emulated version is used _always_ as is the case for `fma`. i.e. at present if `fma` or `round` are _missing_ then you have a hard error (except on VS 2012 and earlier), but if they appear to be _broken_ then the emulated version is used without error. I would like the relevant Windows ports to enable those emulations without needing a special flag (i.e. as for VS 2012 and earlier) but I'd be happy to add more m4sh to make `configure` return a hard error if those functions appear broken anywhere else? The implementation I have put in is cross-compilation ready (this relevant - the Windows builds activate autoconf's cross-compilation mode if you specify `--build` and `--host` which the precheck workers do).
- Finally, the actual test for `fma` revealed that Cygwin32's fma is also broken, just differently from Cygwin64's. I've hardened the testsuite `fma.ml` only to allow the emulated results to be valid if we're actually using our own emulated fma function.

cc @shindere for the autoconf parts (I'm sorry that there are so many autoconf changes coming your way at the moment!)

### CODE REVIEW

**Comment by dra27** [comment]
Just linking in the [AppVeyor run](https://ci.appveyor.com/project/dra27/ocaml/builds/39192821) and [GitHub Actions run](https://github.com/dra27/ocaml/actions/runs/849316601) for this branch from my fork.

**Comment by dra27** [comment]
The hardening of the `fma` test has revealed that the mingw32 and OpenBSD workers do not have a full IEEE-compliant `fma`. The extra commit is now going through [precheck#588](https://ci.inria.fr/ocaml/job/precheck/588/)

**Comment by mmottl** [comment]
Thanks for your hard work on this.  Properly testing numerical functions on one platform is hard enough, I don't want to know how painful it was to test all this on multiple platforms.  Given their idiosyncrasies,  it certainly makes sense to configure the use of default implementations and warnings vs. errors more flexibly.

I can't really say much about Windows-specific stuff, but the overall approach seems fine with me.

**Comment by dra27** [comment]
Thanks! I've had a chat with @octachron earlier, and this can move back to the main PR now!

**Pull request closed without merging**
